### ISSUE TITLE
24.8.1 is not creating pop-up windows

### ISSUE THREAD

**Issue by dspiatkowski** [bitwiseworks/mozilla-os2#85]
24.8.1 (Firefox 24.8.1 Beta 2 (2014-09-26)), attempting to open up a pop-up window fails, nothing actually appears to happen.

I am seeing this while executing the following URL: javascript:void(window.open('http://config.privoxy.org/toggle?mini=y&set=disabled','ijbstatus','width=250,height=100,resizable=yes,scrollbars=no,toolbar=no,location=no,directories=no,status=no,menubar=no,copyhistory=no').focus());

This is a PRIVOXY "Disable" function which is handled locally on my machine by the Privoxy proxy server process. In all previous Firefox releases this would open up a pop-up window (small, as per the size in the URL) where I would be able to temporarily disable Privoxy filtering.

Thanks!

**Comment by dspiatkowski** [comment]
I see that you guys got Beta3 out...since Silvan has added 'task' & 'tests' labels, is this something that you fixed in this release? If so, I'm happy to test...

**Comment by SilvanScherrer** [comment]
If we fixed it, we would have closed the issue ;-) the labels here mean, that it's our task to test first.

**Comment by dspiatkowski** [comment]
Silvan,
LOL...hmm...quite honestly, I do cincerely hope that you would NOT have simply closed the ticket without confirming with the person who reported the issue (that would be me) that the problem has in fact been addressed. This would have required me to test the fix and provide you my results and concurrence to close the ticket.

Coincidentally that is how "issue resolution" process works in my regular IS job, and happens to be how we used to do it back in the days when I was coding stuff day in, day out.

Look, my point merely being this: OS/2 is a tiny community and it is obvious you guys are short-staffed...while I can not provide hands-on coding help I would be very happy to help out with as much of the testing as possible, this means unit-testing as well. 

If you want me to handle the "test" label responsibilies, I'm here for you guys...just trying to help.

**Comment by dmik** [comment]
Dariusz, different situations may exist. Sometimes we are pretty much confident that the problem is fixed and may close the defect without any feedback from the reporter (he is free to reopen the issue if he proves there is still a problem). Sometimes we are not and in this case we leave the issue open until the reporter confirms it works.

In this case there is no any activity here at all since we simply didn't work on this issue at all yet. Thank you for understanding and for your support and help, we appreciate that.

**Comment by SilvanScherrer** [comment]
@dspiatkowski is it still present in ffox 38?

**Comment by dspiatkowski** [comment]
Sorry it took me so long to get back to this...needed to get through the YUM/RPM thing, DLL clean-up and finally the FF upgrade.

Anyways, gentlement, good news to report. In FF 38.8.0 this now works as expected. I think we can close this ticket please (unless you want me to continue checking throughout future releases, no problem, would be happy to do so).

Thanks,
-Dariusz

**Comment by SilvanScherrer** [comment]
closing on reporters request
